My solution
mate-academy/py-taxi-service-search-and-tests pull request #266
Opened 2023-07-19 12:12 UTC by kovaliskoveronika

![car_list](https://github.com/mate-academy/py-taxi-service-search-and-tests/assets/89770594/1af807de-4a17-431f-86d8-3a76b1080c4a)
![driver_list](https://github.com/mate-academy/py-taxi-service-search-and-tests/assets/89770594/8acc4677-402a-412a-966d-4a9117746ed9)
![manufacturer_list](https://github.com/mate-academy/py-taxi-service-search-and-tests/assets/89770594/f4c5a142-e69a-4da8-83f2-1adf69753e50)

2023-07-20 09:57 UTC, YuriiKindrat requested changes

2023-07-20 09:57 UTC, YuriiKindrat commented on taxi/tests/test_views_cars.py
> +        self.assertRedirects(response, reverse("taxi:car-list"))
there is no need to create a new class for every test 
u can create PrivateCarTests class for all of this tests, also it will make ur code more DRY

2023-07-20 09:57 UTC, YuriiKindrat commented on taxi/tests/test_views_cars.py
> +        self.assertRedirects(response, reverse("taxi:car-list"))
also what about toggle assign to car/search feature ?

2023-07-20 09:57 UTC, YuriiKindrat commented on taxi/tests/test_views_drivers.py
> +    def test_car_detail(self):
car list/car detail tests ?

2023-07-20 09:57 UTC, YuriiKindrat commented on taxi/tests/test_views_drivers.py
> +class DriverTest(TestCase):
Private ?

2023-07-20 09:57 UTC, YuriiKindrat commented on taxi/tests/test_views_manufacturer.py
> +class ManufacturedListTest(TestCase):
the same is for this classes as for cars

2023-07-21 15:03 UTC, Oleg-s-s approved these changes
:+1:

2023-10-30 18:37 UTC, closed without merging