Solution
mate-academy/py-taxi-service-search-and-tests pull request #31
Opened 2022-11-09 10:44 UTC by kateryna3k

<img width="1437" alt="Screenshot 2022-11-09 at 11 53 31" src="https://user-images.githubusercontent.com/111740601/200809574-2f83c46b-ef4e-45c8-b59b-08ffeb702493.png">
<img width="1437" alt="Screenshot 2022-11-09 at 11 53 17" src="https://user-images.githubusercontent.com/111740601/200809592-fbf91cf3-fe28-45fb-a578-c3b9ee4fb676.png">
<img width="1437" alt="Screenshot 2022-11-09 at 11 52 53" src="https://user-images.githubusercontent.com/111740601/200809602-9f7f6ef5-c458-4c3b-833e-e6b598e3f26e.png">

2022-11-09 13:44 UTC, Gr1zzZzzly approved these changes

2022-11-10 14:29 UTC, MasterpieceElbow requested changes
Please, update your version with the master's one. Add tests for the searching functionality.

2022-11-17 09:37 UTC, TPolina requested changes

2022-11-17 09:49 UTC, TPolina approved these changes
Good job!

2024-10-02 07:32 UTC, closed without merging