Solution
mate-academy/py-taxi-service-search-and-tests pull request #364
Opened 2023-11-20 18:33 UTC by vshvanska

![driver_search](https://github.com/mate-academy/py-taxi-service-search-and-tests/assets/141127161/eacf2304-f476-4904-8e0c-a20cd13ce5d8)
![manufacturer_search](https://github.com/mate-academy/py-taxi-service-search-and-tests/assets/141127161/d61b6cd4-001e-4b38-b52e-e73815ffdbc3)
![car_search](https://github.com/mate-academy/py-taxi-service-search-and-tests/assets/141127161/b044c60d-8767-4a1d-8c5b-93ad59e9b10f)

2023-11-20 23:13 UTC, mykolamateichuk approved these changes
👍

2023-11-22 14:27 UTC, LiudmylaKulinchenko requested changes

2023-11-22 14:27 UTC, LiudmylaKulinchenko commented on .flake8
> +    tests
Why would you want to ignore tests by flake8?

2023-11-22 14:27 UTC, LiudmylaKulinchenko commented on taxi/tests/test_admin.py
> +        res = self.client.get(url)
use descriptive names, not res

2023-11-23 16:32 UTC, LiudmylaKulinchenko requested changes

2023-11-23 16:32 UTC, LiudmylaKulinchenko commented on .flake8
> +    tests
You should not ignore tests by flake8

2023-11-24 12:36 UTC, LiudmylaKulinchenko requested changes

2023-11-24 12:36 UTC, LiudmylaKulinchenko commented on taxi/tests/test_forms.py
> +            list(manufacturers))
bad formatting

2023-11-24 12:36 UTC, LiudmylaKulinchenko commented on taxi/tests/test_model.py
> +            f"{driver.username} ({driver.first_name} {driver.last_name})")
bad formatting

2023-11-24 13:02 UTC, LiudmylaKulinchenko approved these changes
Good job 👍

2025-01-27 18:58 UTC, closed without merging