added querytransform method for templates and tests for forms, models…
mate-academy/py-taxi-service-search-and-tests pull request #446
Opened 2024-02-12 19:23 UTC by VladyslavShepilov

… and views of taxi app

2024-02-12 19:28 UTC, VladyslavShepilov commented
<img width="1512" alt="Снимок экрана 2024-02-12 в 21 27 57" src="https://github.com/mate-academy/py-taxi-service-search-and-tests/assets/136336159/1259d027-c409-4a92-b9c6-7d242cd2cec6">
<img width="1512" alt="Снимок экрана 2024-02-12 в 21 27 54" src="https://github.com/mate-academy/py-taxi-service-search-and-tests/assets/136336159/0e2efe42-3ddf-4a57-8108-6d64a3cf8014">
<img width="1512" alt="Снимок экрана 2024-02-12 в 21 27 05" src="https://github.com/mate-academy/py-taxi-service-search-and-tests/assets/136336159/b4038196-d141-495f-be15-826802c7c867">
<img width="1512" alt="Снимок экрана 2024-02-12 в 21 26 59" src="https://github.com/mate-academy/py-taxi-service-search-and-tests/assets/136336159/b7daff58-0336-4703-a751-68f9331a63cf">

2024-02-13 09:45 UTC, ArsenPidhoretskyi requested changes

2024-02-14 09:58 UTC, ArsenPidhoretskyi requested changes

2024-02-14 13:15 UTC, vasylhnatiuk approved these changes

2025-10-24 20:36 UTC, closed without merging