solve
mate-academy/py-taxi-service-search-and-tests pull request #685
Opened 2024-09-19 19:38 UTC by Poznanskyi

2024-09-19 19:48 UTC, Poznanskyi commented
![2024-09-19_22-33](https://github.com/user-attachments/assets/5f45445c-8ce2-4c13-b755-65e8ea6ffa3e)
![2024-09-19_22-33_1](https://github.com/user-attachments/assets/9e9a2676-cff7-43c0-bbea-0326e58ec488)
![2024-09-19_22-33_2](https://github.com/user-attachments/assets/ecf2b7fd-01b7-4376-8089-be09b5f866aa)

2024-09-21 18:24 UTC, ABaidin commented
FAILED (failures=4, errors=6)

I guess you are busy with your project now

2024-09-21 18:40 UTC, ABaidin requested changes
I guess you are busy with your project now

2024-09-30 11:09 UTC, Oleksl888 requested changes

2024-09-30 11:09 UTC, Oleksl888 commented on taxi/views.py
> +from .forms import (
do not use relative imports

2024-09-30 11:09 UTC, Oleksl888 commented on taxi/tests/test_forms.py
> +        self.assertEqual(cars.first().model, "test1")
Here would make sense to include assert that 'qwe223' is not in result to be 100% sure that search returns correct result

2024-09-30 20:22 UTC, LiudmylaKulinchenko approved these changes
Good job 🔥

2025-09-18 13:13 UTC, closed without merging